defaults:
  - config1
  - override hydra/launcher: submitit_slurm
  - _self_

hydra:
  sweeper:
    params:
      model.network.hdims: choice([100], [100, 100], [100, 100, 100], [100, 100, 100, 100])
      model.network.seed: range(0, 6, 1)
      task.training_comps: choice([[4],[4]], [[0],[0]], [[0,8],[0,8]], [[2,6],[2,6]])
  launcher:
    cpus_per_task: 1
    mem_gb: 10
    timeout_min: 240
    exclude: ax[01,17]
task:
  task_values: [[-4,-3,-2,-1,0,1,2,3,4], [-4,-3,-2,-1,0,1,2,3,4]]
model:
  trainer_config:
    max_epochs: 100000
    lr: 1e-4
    auto_lr_find: false
    analyse_every_n_epoch: -1
    early_stopping: true
    early_stopping_stopping_threshold: 1e-4
    early_stopping_divergence_threshold: 200
    inference_mode: false
    momentum: 0.9
    optimizer: adam
  network:
    log_scaling: -1
analysis: [additivity, feature_sim, ntk_sim]
