defaults:
  - config1
  - override model/network: convnet
  - override task: context_dependence
  - override hydra/launcher: submitit_slurm
  - override embedding.input_generator: image
  - _self_

hydra:
  sweeper:
    params:
      embedding.input_generator.seed: range(0,10,1)
      embedding.input_generator.distance: choice(0, 5, 10, 15, 20)
      model.trainer_config.criterion: choice(mse, crossentropy)
  launcher:
    cpus_per_task: 1
    gres: gpu:1
    mem_gb: 15
    timeout_min: 600
    exclude: ax[01,06,17]
task:
  contexts: 2
  features: [6,6]
  context_to_feature: [0,1]
  feature_to_response: [[-1,-1,-1,1,1,1], [-1,-1,-1, 1, 1,1]]
  leftout_conjunctions: [{1: [0,1,2], 2: [3,4,5]}]
embedding:
  input_generator:
    n_training_samples_total: 30000
    n_training_imgs: 200
    separate_channels: true
    permutation: random
    permutation_seed: ${embedding.input_generator.seed}
model:
  trainer_config:
    accelerator: gpu
    max_epochs: 100
    lr: 1e-4
    analyse_first_n_epochs: -1
    momentum: 0.9
    batch_training: true
    batch_testing: true
    num_workers: 2
    test_batch_size: 256
    check_val_every_n_epoch: 10
  network:
    seed: ${embedding.input_generator.seed}
analysis: [additivity, feature_sim]
metrics: [mse, binary_accuracy]
